import { NextResponse } from "next/server";
import { connectDB } from "@/lib/dbconnect";
import Charity from "@/models/Charity";

export async function GET() {
  try {
    await connectDB();

    const sampleCharities = [
      // 🌿 Environment & Conservation (10)
      {
        title: "GreenTeam",
        desc: "A nonprofit working to preserve forests and promote sustainable living across India.",
        website: "https://www.greenteam.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 120000,
      },
      {
        title: "EcoRoots",
        desc: "Planting trees in deforested areas and promoting community forest projects.",
        website: "https://www.ecoroots.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 95000,
      },
      {
        title: "CleanSeas",
        desc: "Dedicated to cleaning beaches and reducing plastic pollution in coastal cities.",
        website: "https://www.cleanseasfoundation.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 75000,
      },
      {
        title: "PlantTomorrow",
        desc: "Focused on reforestation and carbon offset projects across South Asia.",
        website: "https://www.planttomorrow.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 123000,
      },
      {
        title: "CleanAirNow",
        desc: "Creating air quality awareness and supporting clean energy initiatives.",
        website: "https://www.cleanairnow.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 99000,
      },
      {
        title: "OceanLife",
        desc: "Working to protect marine ecosystems and endangered ocean species.",
        website: "https://www.oceanlife.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 108000,
      },
      {
        title: "EarthGuard",
        desc: "Community-led initiatives to combat deforestation and promote waste recycling.",
        website: "https://www.earthguard.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 68000,
      },
      {
        title: "SolarFuture",
        desc: "Providing solar energy panels to schools and villages in remote areas.",
        website: "https://www.solarfuture.in",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 78000,
      },
      {
        title: "RiverRevive",
        desc: "Cleaning and restoring polluted rivers and supporting water conservation projects.",
        website: "https://www.riverrevive.org",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 87000,
      },
      {
        title: "ClimateActionNow",
        desc: "Raising awareness about climate change and encouraging sustainable practices.",
        website: "https://www.climateactionnow.in",
        img: "/globe.svg",
        category: "Environment & Conservation",
        verified: true,
        region: "India",
        donationsReceived: 115000,
      },

      // 🍛 Hunger & Poverty Relief (9)
      {
        title: "FoodRelief",
        desc: "Delivering meals to the homeless and supporting food banks nationwide.",
        website: "https://www.foodrelief.in",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 95000,
      },
      {
        title: "HopeShelter",
        desc: "Providing shelter and vocational training for homeless individuals.",
        website: "https://www.hopeshelter.org",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 102000,
      },
      {
        title: "MealsForAll",
        desc: "Partnering with restaurants to distribute surplus food to people in need.",
        website: "https://www.mealsforall.org",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 60000,
      },
      {
        title: "StreetSmiles",
        desc: "Providing food and warm clothes for street dwellers during winters.",
        website: "https://www.streetsmiles.in",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 78000,
      },
      {
        title: "GrainForLife",
        desc: "Collecting grains from households to feed low-income communities.",
        website: "https://www.grainforlife.org",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 54000,
      },
      {
        title: "DignityDrive",
        desc: "Empowering poor families through housing, hygiene, and food programs.",
        website: "https://www.dignitydrive.in",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 91000,
      },
      {
        title: "CareKitchens",
        desc: "Running mobile kitchens to serve nutritious meals in disaster zones.",
        website: "https://www.carekitchens.org",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 87000,
      },
      {
        title: "FeedHope",
        desc: "A nationwide campaign to eradicate hunger by distributing daily meals.",
        website: "https://www.feedhope.in",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 100000,
      },
      {
        title: "HelpingHands",
        desc: "Community-run initiative to provide food and basic supplies to slum areas.",
        website: "https://www.helpinghands.org",
        img: "/globe.svg",
        category: "Hunger & Poverty Relief",
        verified: true,
        region: "India",
        donationsReceived: 73000,
      },

      // ❤️ Health & Medical Aid (10)
      {
        title: "HealthBridge",
        desc: "Providing free healthcare camps and medicines to low-income communities.",
        website: "https://www.healthbridge.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 130000,
      },
      {
        title: "VisionCare",
        desc: "Organizing free eye checkup camps and providing spectacles to those in need.",
        website: "https://www.visioncareindia.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 42000,
      },
      {
        title: "HealHearts",
        desc: "Providing heart surgeries for children from low-income families.",
        website: "https://www.healheartsfoundation.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 150000,
      },
      {
        title: "SmileAid",
        desc: "Providing dental hygiene awareness and free dental checkups in rural areas.",
        website: "https://www.smileaid.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 47000,
      },
      {
        title: "CareMeds",
        desc: "Delivering life-saving medicines to patients in rural and tribal areas.",
        website: "https://www.caremeds.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 88000,
      },
      {
        title: "BloodConnect",
        desc: "Connecting blood donors with emergency patients in real time.",
        website: "https://www.bloodconnect.in",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 72000,
      },
      {
        title: "MindMatters",
        desc: "Offering free online counseling and mental health workshops.",
        website: "https://www.mindmatters.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 56000,
      },
      {
        title: "CancerAid",
        desc: "Financially assisting cancer patients for treatment and palliative care.",
        website: "https://www.canceraidfoundation.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 132000,
      },
      {
        title: "HeartOfHope",
        desc: "Providing post-surgery rehabilitation for cardiac patients.",
        website: "https://www.heartofhope.in",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 67000,
      },
      {
        title: "HealthReach",
        desc: "Mobile health vans serving remote villages lacking basic healthcare.",
        website: "https://www.healthreach.org",
        img: "/globe.svg",
        category: "Health & Medical Aid",
        verified: true,
        region: "India",
        donationsReceived: 110000,
      },
            // 📚 Education & Skills (10)
      {
        title: "EduRise",
        desc: "Providing free primary education to children in rural and slum areas.",
        website: "https://www.edurise.in",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 96000,
      },
      {
        title: "SkillBridge",
        desc: "Empowering youth through job skill training and digital literacy programs.",
        website: "https://www.skillbridge.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 87000,
      },
      {
        title: "ReadToGrow",
        desc: "Distributing books and establishing libraries in underprivileged schools.",
        website: "https://www.readtogrow.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 55000,
      },
      {
        title: "TechForTeens",
        desc: "Teaching coding and robotics to children in low-income communities.",
        website: "https://www.techforteens.in",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 100000,
      },
      {
        title: "BrightSteps",
        desc: "Scholarships and mentorship programs for students pursuing higher education.",
        website: "https://www.brightsteps.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 114000,
      },
      {
        title: "VillageEducate",
        desc: "Training rural teachers and improving school infrastructure.",
        website: "https://www.villageeducate.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 71000,
      },
      {
        title: "WomenLearn",
        desc: "Providing adult literacy and skill workshops for women in rural regions.",
        website: "https://www.womenlearn.in",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 63000,
      },
      {
        title: "SchoolKit",
        desc: "Donating stationery and school bags to underprivileged children.",
        website: "https://www.schoolkit.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 38000,
      },
      {
        title: "TeachForward",
        desc: "Recruiting volunteers to teach underfunded schools in slum communities.",
        website: "https://www.teachforward.org",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 88000,
      },
      {
        title: "STEMBridge",
        desc: "Encouraging girls to pursue STEM careers through scholarships and mentorships.",
        website: "https://www.stembridge.in",
        img: "/globe.svg",
        category: "Education & Skills",
        verified: true,
        region: "India",
        donationsReceived: 99000,
      },

      // 👩‍👧 Women & Children (10)
      {
        title: "SafeHaven",
        desc: "Supporting women facing domestic violence with shelter and counseling.",
        website: "https://www.safehaven.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 94000,
      },
      {
        title: "ChildBright",
        desc: "Helping orphaned children find education and long-term care.",
        website: "https://www.childbright.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 105000,
      },
      {
        title: "GirlRise",
        desc: "Promoting girl child education and leadership programs in rural India.",
        website: "https://www.girlrise.in",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 111000,
      },
      {
        title: "MomsMatter",
        desc: "Providing healthcare support to expecting and new mothers in villages.",
        website: "https://www.momsmatter.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 87000,
      },
      {
        title: "HerSteps",
        desc: "Microloan and entrepreneurship support for women-led small businesses.",
        website: "https://www.hersteps.in",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 93000,
      },
      {
        title: "SafeChild",
        desc: "Advocating for child safety and rescuing children from trafficking.",
        website: "https://www.safechildfoundation.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 97000,
      },
      {
        title: "WomenForChange",
        desc: "Educating women on rights, equality, and financial independence.",
        website: "https://www.womenforchange.in",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 88000,
      },
      {
        title: "BrightFutureGirls",
        desc: "Running after-school learning centers for underprivileged girls.",
        website: "https://www.brightfuturegirls.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 69000,
      },
      {
        title: "AngelCare",
        desc: "Providing nutrition and medical care for malnourished children.",
        website: "https://www.angelcare.in",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 78000,
      },
      {
        title: "DignityMothers",
        desc: "Focused on empowering widowed and abandoned mothers with employment.",
        website: "https://www.dignitymothers.org",
        img: "/globe.svg",
        category: "Women & Children",
        verified: true,
        region: "India",
        donationsReceived: 82000,
      },

      // 🌪️ Disaster Relief (8)
      {
        title: "ReliefNow",
        desc: "Emergency disaster response for floods, earthquakes, and cyclones.",
        website: "https://www.reliefnow.org",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 132000,
      },
      {
        title: "RescueAid",
        desc: "Providing food, medical aid, and shelter during natural calamities.",
        website: "https://www.rescueaid.org",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 98000,
      },
      {
        title: "FloodRelief",
        desc: "Focused on supporting flood-affected regions in Assam and Bihar.",
        website: "https://www.floodrelief.in",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 89000,
      },
      {
        title: "RapidResponse",
        desc: "First responders during natural disasters, providing emergency supplies.",
        website: "https://www.rapidresponse.org",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 112000,
      },
      {
        title: "ReliefWings",
        desc: "Mobilizing volunteers to rebuild disaster-struck homes.",
        website: "https://www.reliefwings.in",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 75000,
      },
      {
        title: "QuakeHelp",
        desc: "Supplying temporary housing and essentials post-earthquake.",
        website: "https://www.quakehelp.org",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 67000,
      },
      {
        title: "HealAfterStorm",
        desc: "Providing trauma care and community rebuilding support post-disaster.",
        website: "https://www.healafterstorm.org",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 82000,
      },
      {
        title: "HelpIndiaNow",
        desc: "Multi-purpose emergency response organization covering all states.",
        website: "https://www.helpindianow.in",
        img: "/globe.svg",
        category: "Disaster Relief",
        verified: true,
        region: "India",
        donationsReceived: 120000,
      },

      // 🐾 Animals & Wildlife (8)
      {
        title: "PawsRescue",
        desc: "Rescuing stray animals and providing medical aid and shelter.",
        website: "https://www.pawsrescue.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 98000,
      },
      {
        title: "WildCare",
        desc: "Protecting endangered species through conservation programs.",
        website: "https://www.wildcarefoundation.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 110000,
      },
      {
        title: "FeatherHaven",
        desc: "A bird sanctuary providing rescue and rehabilitation services.",
        website: "https://www.featherhaven.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 67000,
      },
      {
        title: "HappyTails",
        desc: "Running adoption drives and community pet sterilization programs.",
        website: "https://www.happytails.in",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 84000,
      },
      {
        title: "OceanGuardians",
        desc: "Saving sea turtles and marine mammals from illegal hunting.",
        website: "https://www.oceanguardians.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 103000,
      },
      {
        title: "JungleWatch",
        desc: "Working with forest departments to prevent poaching and protect habitats.",
        website: "https://www.junglewatch.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 97000,
      },
      {
        title: "AnimalAid",
        desc: "Providing medical treatment to street animals injured in accidents.",
        website: "https://www.animalaid.in",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 91000,
      },
      {
        title: "SavePaws",
        desc: "Community-run initiative for sterilization and vaccination of stray dogs.",
        website: "https://www.savepaws.org",
        img: "/globe.svg",
        category: "Animals & Wildlife",
        verified: true,
        region: "India",
        donationsReceived: 68000,
      },

      // 🙏 Individual Fundraisers (10)
      {
        title: "HelpRameshSurgery",
        desc: "Raising funds for Ramesh’s urgent kidney transplant operation.",
        website: "https://www.helpramesh.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 45000,
      },
      {
        title: "SavePriya",
        desc: "Collecting funds for Priya’s cancer treatment and post-chemo care.",
        website: "https://www.savepriya.in",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 56000,
      },
      {
        title: "SupportAnkit",
        desc: "Supporting Ankit’s recovery from a severe road accident.",
        website: "https://www.supportankit.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 72000,
      },
      {
        title: "HelpNehaStudy",
        desc: "Funding Neha’s higher education dream in medical school.",
        website: "https://www.helpneha.in",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 38000,
      },
      {
        title: "SaveSohan",
        desc: "Helping Sohan recover from a spinal injury after an accident.",
        website: "https://www.savesohan.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 62000,
      },
      {
        title: "CareForManju",
        desc: "Raising funds for Manju’s heart surgery scheduled next month.",
        website: "https://www.careformanju.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 54000,
      },
      {
        title: "SupportRaviEducation",
        desc: "Helping Ravi pursue computer engineering through crowdfunding.",
        website: "https://www.supportravi.in",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 41000,
      },
      {
        title: "HelpLalitaRecover",
        desc: "Funds needed for Lalita’s post-burn treatment and rehabilitation.",
        website: "https://www.helplalita.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 37000,
      },
      {
        title: "AidRahul",
        desc: "Supporting Rahul’s long-term physiotherapy after a head injury.",
        website: "https://www.aidrahul.in",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 48000,
      },
      {
        title: "HelpSnehaWalkAgain",
        desc: "Raising funds for Sneha’s prosthetic leg after an accident.",
        website: "https://www.helpsneha.org",
        img: "/globe.svg",
        category: "Individual Fundraisers",
        verified: true,
        region: "India",
        donationsReceived: 53000,
      },
    ];

    await Charity.insertMany(sampleCharities);

    return NextResponse.json({ message: "✅ 75 Charities seeded successfully!" });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: "Failed to seed charities" }, { status: 500 });
  }
}

